<a href="https://colab.research.google.com/github/jcjimenezb123/MetodosNumericosPython/blob/master/ED2O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Método del disparo

In [1]:
import numpy as np
from scipy.integrate import odeint
import plotly.express as px

In [2]:
def f(U,L):
  u1,u2=U
  a=0.01
  Ta=25
  du1dx=u2
  du2dx=a*(u1-Ta)

  return np.array([du1dx,du2dx])

In [3]:
L=10
Tx1=50
Tx2=200
longitud=np.linspace(0,L)

dT=10

U10=odeint(f,[Tx1,dT],longitud)
U10

array([[ 50.        ,  10.        ],
       [ 52.0461651 ,  10.05310651],
       [ 54.10359437,  10.11040019],
       [ 56.17314553,  10.17190494],
       [ 58.25568056,  10.23764636],
       [ 60.3520668 ,  10.30765183],
       [ 62.46317742,  10.38195052],
       [ 64.58989175,  10.46057337],
       [ 66.73309558,  10.54355314],
       [ 68.89368156,  10.63092437],
       [ 71.07254959,  10.72272346],
       [ 73.27060719,  10.81898864],
       [ 75.48876987,  10.91976002],
       [ 77.7279615 ,  11.02507956],
       [ 79.98911473,  11.13499113],
       [ 82.27317134,  11.24954051],
       [ 84.58108267,  11.36877541],
       [ 86.91381002,  11.4927455 ],
       [ 89.27232499,  11.62150241],
       [ 91.65760992,  11.75509978],
       [ 94.07065822,  11.89359323],
       [ 96.51247488,  12.03704043],
       [ 98.98407701,  12.18550114],
       [101.48649407,  12.3390372 ],
       [104.02076832,  12.49771256],
       [106.58795533,  12.66159332],
       [109.18912433,  12.83074773],
 

In [ ]:
px.scatter(x=longitud,y=U10[:,0])

In [4]:
dT=20

U20=odeint(f,[Tx1,dT],longitud)
U20

array([[ 50.        ,  20.        ],
       [ 54.08712307,  20.05518904],
       [ 58.18636042,  20.1187312 ],
       [ 62.29942016,  20.19065297],
       [ 66.42801539,  20.2709843 ],
       [ 70.57386565,  20.35975865],
       [ 74.73869778,  20.45701299],
       [ 78.92424647,  20.56278784],
       [ 83.13225502,  20.67712724],
       [ 87.36447609,  20.80007882],
       [ 91.62267245,  20.93169379],
       [ 95.90861765,  21.07202697],
       [100.22409683,  21.22113682],
       [104.57090742,  21.37908542],
       [108.9508599 ,  21.54593858],
       [113.36577859,  21.72176579],
       [117.81750235,  21.9066403 ],
       [122.30788536,  22.10063911],
       [126.8387978 ,  22.30384298],
       [131.41212679,  22.51633655],
       [136.02977724,  22.73820834],
       [140.69367244,  22.96955075],
       [145.40575492,  23.21046016],
       [150.1679873 ,  23.4610369 ],
       [154.98235308,  23.72138535],
       [159.8508575 ,  23.99161393],
       [164.77552832,  24.27183519],
 

In [5]:
fig=px.line(x=longitud,y=U10[:,0])
fig.add_scatter(x=longitud,y=U20[:,0])
fig.show()

In [6]:
dT=np.interp(200,[U10[-1,0],U20[-1,0]],[10,20])
dT

11.608478760744338

In [7]:
U=odeint(f,[Tx1,dT],longitud)
U

array([[ 50.        ,  11.60847876],
       [ 52.37444885,  11.66192024],
       [ 54.76029862,  11.72021898],
       [ 57.15854379,  11.78339928],
       [ 59.57018326,  11.85148745],
       [ 61.99622143,  11.92451186],
       [ 64.43766879,  12.00250292],
       [ 66.89554226,  12.08549311],
       [ 69.37086554,  12.17351701],
       [ 71.86466962,  12.26661126],
       [ 74.3779932 ,  12.36481465],
       [ 76.91188309,  12.46816808],
       [ 79.46739467,  12.5767146 ],
       [ 82.04559234,  12.69049941],
       [ 84.64754992,  12.80956992],
       [ 87.27435117,  12.9339757 ],
       [ 89.92709017,  13.06376859],
       [ 92.60687185,  13.19900265],
       [ 95.31481237,  13.33973421],
       [ 98.05203955,  13.48602187],
       [100.8196934 ,  13.63792654],
       [103.61892665,  13.7955115 ],
       [106.45090529,  13.95884238],
       [109.31680884,  14.12798723],
       [112.21783098,  14.30301649],
       [115.15518   ,  14.48400307],
       [118.13007934,  14.67102235],
 

In [8]:
px.scatter(x=longitud,y=U[:,0])

#Método de diferencias finitas

In [ ]:
a=0.01
n=100
L=10
longitud=np.linspace(0,L,n+1)
h=L/n
Ta=25
T0=50
Tn=200

In [ ]:
A=np.diag([1]*(n-2),-1) + np.diag([-(2+a*h**2)]*(n-1)) + np.diag([1]*(n-2),1)
A

array([[-2.0002,  1.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 1.    , -2.0002,  1.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  1.    , -2.0002, ...,  0.    ,  0.    ,  0.    ],
       ...,
       [ 0.    ,  0.    ,  0.    , ..., -2.0002,  1.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  1.    , -2.0002,  1.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  1.    , -2.0002]])

In [ ]:
b=np.array([-a*h**2*Ta]*(n-1))
b[0]=b[0]-T0
b[-1]=b[-1]-Tn
b

array([-5.00050e+01, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.00000e-03,
       -5.00000e-03, -5.00000e-03, -5.00000e-03, -5.000

In [ ]:
T=np.linalg.solve(A,b)
T=np.append(T0,T)
T=np.append(T,Tn)
T

In [ ]:
px.scatter(x=longitud,y=T)