<a href="https://colab.research.google.com/github/jcjimenezb123/MetodosNumericosPython/blob/master/SENL_metodos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resuelva el siguiente sistema de ecuaciones
no lineales, utilizando el método de punto fijo multivariable:

$$
3x_1-cos(x_2x_3)-\frac{1}{2}=0\\
x_1^2-81(x_2+0.1)^2+sin(x_3)+1.06=0\\
e^{-x_1x_2}+20x_3+\frac{10\pi -3}{3}=0
$$

Primero se despeja xi de la i-ésima ecuación de la siguiente forma

$$
x_1=\frac{1}{3}cos(x_2x_3)+\frac{1}{6}\\
x_2=\frac{1}{9}\sqrt{x_1^2+sin(x_3)+1.06}-0.1\\
x_3=-\frac{1}{20}e^{-x_1x_2}+\frac{10\pi -3}{60}
$$

In [1]:
import numpy as np

In [2]:
def pfm(g,x,imax=100,tol=1e-8):
  cumple=False
  k=0
  while (not cumple and k<imax):
    x0=x.copy()
    x=g(x0)
    
    norma=np.linalg.norm(x-x0)
    print(x,norma)
    cumple=norma<tol
    k+=1
  if k<imax:
    return x
  else:
    print('No converge')

In [5]:
def g(x):
  x1,x2,x3=x
  g1=np.cos(x2*x3)/3+1/6
  g2=np.sqrt(x1**2+np.sin(x3)+1.06)/9-0.1
  g3=-np.exp(-x1*x2)/20-(10*np.pi-3)/60
  return np.array([g1,g2,g3])

In [6]:
x=np.array([0,0,0])

sol=pfm(g,x,tol=1e-10)
sol

[ 0.5         0.01439589 -0.52359878] 0.7241290765257544
[ 0.49999053  0.         -0.52324017] 0.014400359345972486
[ 5.00000000e-01  1.85861736e-05 -5.23598776e-01] 0.0003592112676262878
[ 0.5         0.         -0.52359831] 1.8591980819367472e-05
[ 5.00000000e-01  2.48385687e-08 -5.23598776e-01] 4.65315596135859e-07
[ 0.5         0.         -0.52359877] 2.4846329499278034e-08
[ 5.00000000e-01  3.31957239e-11 -5.23598776e-01] 6.218508303745252e-10
[ 0.5         0.         -0.52359878] 3.3206095956114756e-11


array([ 0.5       ,  0.        , -0.52359878])

Resuelva el siguiente sistema de ecuaciones no lineales, utilizando el m\'etodo de Newton-Raphson multivariable

$$
f_1(x_1,x_2)=2x_1-x_2-e^{-x_1}=0\\
f_2(x_1,x_2)=-x_1+2x_2-e^{-x_2}=0
$$

Obtenemos el Jacobiano del sistema:

$$
\begin{pmatrix}
\frac{\partial f_1}{\partial x_1}=2 + e^{-x_1} & \frac{\partial f_1}{\partial x_2}=-1\\
\frac{\partial f_2}{\partial x_1}=-1 & \frac{\partial f_2}{\partial x_2} =2 + e^{-x_2}\\
\end{pmatrix}
$$

In [ ]:
import numpy as np

def newtonRaphsonMV(F,J,x,imax =100,tol=1e-8):
  cumple = False
  k=0
  while ( not cumple and k< imax ):
    deltax =np.linalg.solve(J(x),-F(x))
    x = x + deltax
    print ( f' iteracion :{k} - > {x} ')
    cumple =np.linalg.norm(F(x)) <= tol
    k +=1
  if k< imax :
    return x
  else:
    raise ValueError ( 'La funcion no converge ')

In [ ]:
def f(x):
  x1,x2=x
  return np.array([2*x1-x2-np.exp(-x1),\
                   -x1 + 2*x2 - np. exp (-x2) ])

In [ ]:
def j(x):
  x1,x2=x
  return np.array([[2 + np.exp(-x1),-1],\
                   [-1, 2 + np.exp (-x2) ]])

In [ ]:
x0=np.array([-5.,-5.])
raiz = newtonRaphsonMV(f,j,x0)
raiz

 iteracion :0 - > [-3.9732286 -3.9732286] 
 iteracion :1 - > [-2.91832728 -2.91832728] 
 iteracion :2 - > [-1.82000345 -1.82000345] 
 iteracion :3 - > [-0.70566754 -0.70566754] 
 iteracion :4 - > [0.19703885 0.19703885] 
 iteracion :5 - > [0.53974367 0.53974367] 
 iteracion :6 - > [0.56700632 0.56700632] 
 iteracion :7 - > [0.56714329 0.56714329] 


array([0.56714329, 0.56714329])

In [ ]:
from scipy.optimize import newton,newton_krylov,anderson,broyden1,broyden2,diagbroyden

In [ ]:
sol=newton(f,x0)
sol

array([0.56714329, 0.56714329])

In [ ]:
sol=newton_krylov(f,x0)
sol

array([0.56714329, 0.56714329])

In [ ]:
sol=anderson(f,x0)
sol

array([0.56714315, 0.56714315])

In [ ]:
sol=broyden1(f,x0)
sol

array([0.56714177, 0.56714177])

In [ ]:
sol=broyden2(f,x0)
sol

array([0.56714177, 0.56714177])

In [ ]:
sol=diagbroyden(f,x0)
sol

array([0.56714057, 0.56714057])