<a href="https://colab.research.google.com/github/jcjimenezb123/MetodosNumericosPython/blob/master/SistemasEcuacionesLineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sistemas de ecuaciones lineales

##Métodos Directos

Resolver el siguiente sistema lineal

$$
\begin{array}{ccccccc}
x&+&y&+&z&=&6\\
&&2y&+&5z&=&-4\\
2x&+&5y&-&z&=&27\\
\end{array}
$$

In [ ]:
import numpy as np
import scipy as sp

In [ ]:
#se crea la matriz de coeficientes del sistema a resolver
A=np.array([[1,1,1],
            [0,2,5],
            [2,5,-1]])
#se crea el vector de los terminos independientes
b=np.array([[6,-4,27]])

In [ ]:
A

array([[ 1,  1,  1,  6],
       [ 0,  2,  5, -4],
       [ 2,  5, -1, 27]])

In [ ]:
Ab=np.concatenate((A,b.T),axis=1) #se crea la matriz extendida concatenando el vector b como una columna (axis=1)
n=np.size(A,axis=1) #regresa el numero de columnas de A, es decir, el numero de incognitas

In [ ]:
Ab

3

Validar si tiene solucion unica por el teorema de **Rouche-Frobenius**

In [ ]:
np.linalg.matrix_rank(Ab)

3

In [ ]:
solucion_unica = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)==n
solucion_unica

True

Resolver el sistema usando el metodo de **Gauss-Jordan**

In [ ]:
import sympy as sy

In [ ]:
reduccion,_=sy.Matrix(Ab).rref() #rref (row reduced echelon form), es decir, el metodo de Gauss-Jordan
reduccion

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

por lo tanto el conjunto solucion es

* $x=5$
* $y=3$
* $z=-2$

Aplicando el metodo de **inversa-multiplicacion**

In [ ]:
#se obtiene la inversa de la matriz de coeficientes A
Ainv=np.linalg.inv(A)
Ainv

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

In [ ]:
x=Ainv.dot(b.T) #se multiplica la inversa de A por el vector b
x

array([[ 5.],
       [ 3.],
       [-2.]])

Aplicando la regla de **Cramer**

In [ ]:
DetA=np.linalg.det(A)
x=np.empty(n)

for i in range(n):
  Ax=A.copy()
  Ax[:,i]=b.copy()
  DetAx=np.linalg.det(Ax)
  x[i]=DetAx/DetA

print(x)

[ 5.  3. -2.]


Se aplica la funcion **solve** de numpy

In [ ]:
x=np.linalg.solve(A,b.T)
x

array([[ 5.],
       [ 3.],
       [-2.]])

##Sistemas homogeneos $Ax=0$

Balancear la siguiente ecuación química

$$
x_1Pb(N_3)_2 + x_2Cr(MnO_4)_2 \rightarrow x_3Cr_2O_3 + x_4MnO_2 + x_5Pb_3O_4 + x_6NO
$$

Balance por elemento

* $Pb: x_1 = 3x_5 \Rightarrow x1–3x_5 = 0$
* $N: 6x_1 = x_6 \Rightarrow 6x_1 -x_6 = 0$
* $Cr: x_2 = 2x_3 \Rightarrow x_2–2x_3 = 0$
* $Mn: 2x_2 = x_4 \Rightarrow 2x_2–x_4 = 0$
* $O: 8x_2 = 3x_3 +2x_4 +4x_5 +x_6 \Rightarrow 8x_2 -3x_3 -2x_4 -4x_5 -x_6 = 0$

El sistema de ecuaciones lineales es

$$
\begin{pmatrix}
1& 0& 0& 0& -3& 0\\
6& 0& 0& 0& 0& -1\\
0& 1& -2& 0& 0& 0\\
0& 2& 0& -1& 0& 0\\
0& 8& -3& -2& -4& -1
\end{pmatrix}
$$

In [ ]:
import numpy as np
A=np.array([[1 , 0, 0, 0,-3, 0 ],
            [ 6 , 0, 0, 0, 0,-1 ],
            [ 0 , 1,-2, 0, 0, 0 ],
            [ 0 , 2, 0,-1, 0, 0 ],
            [ 0 , 8,-3,-2,-4,-1 ]])

b=np.array([[0 ,0 ,0 ,0 ,0]])

In [ ]:
Ab=np.concatenate((A,b.T),axis=1)
n=np.size(A,axis=1)

In [ ]:
Ab

array([[ 1,  0,  0,  0, -3,  0,  0],
       [ 6,  0,  0,  0,  0, -1,  0],
       [ 0,  1, -2,  0,  0,  0,  0],
       [ 0,  2,  0, -1,  0,  0,  0],
       [ 0,  8, -3, -2, -4, -1,  0]])

In [ ]:
solucion_unica = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)==n
solucion_unica

False

In [ ]:
solucion_multiple = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)<n
solucion_multiple

True

In [ ]:
import sympy as sy

reduccion,_=sy.Matrix(Ab).rref()
reduccion

Matrix([
[1, 0, 0, 0, 0,   -1/6, 0],
[0, 1, 0, 0, 0, -22/45, 0],
[0, 0, 1, 0, 0, -11/45, 0],
[0, 0, 0, 1, 0, -44/45, 0],
[0, 0, 0, 0, 1,  -1/18, 0]])

Por lo tanto el sistema tiene multiples soluciones y guarda las siguientes proporciones

* $x_1=1/6x_6$
* $x_2=22/45x_6$
* $x_3=11/45x_6$
* $x_4=44/45x_6$
* $x_5=1/18x_6$

el conjunto solucion queda expresado como

$$
(1/6x_6,22/45x_6,11/45x_6,44/45x_6,1/18x_6,x_6)
$$

para resolver el problema del balanceo de la reaccion quimica se debe buscar un valor de $x_6$ de tal manera que los valores del resto de las incognitas sea un entero.

por ejemplo $x_6=90$



In [ ]:
x6=90
x1=-x6*reduccion[0,-2]
x2=-x6*reduccion[1,-2]
x3=-x6*reduccion[2,-2]
x4=-x6*reduccion[3,-2]
x5=-x6*reduccion[4,-2]

print(x1,x2,x3,x4,x5,x6)

15 44 22 88 5 90


Por lo tanto la reaccion balanceada es

$$
15Pb(N_3)_2 + 44Cr(MnO_4)_2 \rightarrow 22Cr_2O_3 + 88MnO_2 + 5Pb_3O_4 + 90NO
$$

##Metodos iterativos

En el metodo de Jacobi se descompone la matriz de coeficientes $A$ en dos matrices, una se compone de los elementos de la diagonal $D_{i,i}=A_{i,i}$. La matriz $D$ no debe tener elementos cero, si fuera asi se deben intercambiar los renglones para evitar el caso. La otra matriz es el resto de los elementos, es decir los elementos que no son la diagonal $R_{i,j}=A_{i,j}$ de tal manera que $A=D+R$.

\begin{array}
A&A=&
\begin{pmatrix}
A_{1,1} & A_{1,2} & \cdots & A_{1,n}\\
A_{2,1} & A_{2,2} & \cdots & A_{2,n}\\
\vdots & \vdots & \ddots & \vdots\\
A_{n,1} & A_{n,2} & \cdots & A_{n,n}\\
\end{pmatrix}
&D&=&
\begin{pmatrix}
A_{1,1} &0 & \cdots & 0\\
0 & A_{2,2} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & A_{n,n}\\
\end{pmatrix}
$\\
 & \\
R&=&
\begin{pmatrix}
0 & A_{1,2} & \cdots & A_{1,n}\\
A_{2,1} & 0 & \cdots & A_{2,n}\\
\vdots & \vdots & \ddots & \vdots\\
A_{n,1} & A_{n,2} & \cdots & 0\\
\end{pmatrix}
\end{array}

Por lo tanto, la ecuacion que describe un sistema de ecuaciones lineales $Ax=b$ ahora se expresa como $[D+R]x=b$.

\begin{equation*}
\begin{split}
Dx+Rx&=b\\
Dx&=b-Rx\\
D^{-1}Dx&=D^{-1}(b-Rx)\\
x&=D^{-1}(b-Rx)
\end{split}
\end{equation*}

Ecuacion iterativa de Jacobi
$$
x^{(k+1)}=D^{-1}\left( b-Rx^{(k)} \right)
$$

La ecuacion iterativa de Jacobi se inicia con valores supuestos $x^{(k)}$ y la ecuacion iterativa obtiene los siguientes valores $x^{(k+1)}$. El proceso se repite hasta que la diferencia absoluta entre $x^{(k+1)}$ y $x^{(k)}$ sea minima.


En una columna de 5 platos, se requiere absorber benceno contenido en una corriente de gas V, con aceite L que circula a contracorriente del gas. Considerese que el benceno transferido no altera sustancialmente el numero de moles de V y L fluyendo a contracorriente, que relacion de equilibrio esta dada por la ley de Henry ($y = mx$) y que la columna opera a regimen permanente. Calcule la composicion en cada plato.

\begin{array}
xDatos:&V = 100 & moles/min\\
 & L = 500 & moles/min\\
 & y_0 = 0.09 & \text{fraccion molar de benceno en V}\\
 & x_0 = 0.0 & \text{fraccion de benceno en L (el aceite entra por el domo sin benceno)}\\
 & m = 0.12
\end{array}

Sistema

\begin{pmatrix}
-512x_5 & 12x_4 & 0 & 0 & 0 & 0\\
500x_5 & -512x_4 & 12x_3 & 0 & 0 & 0\\
0 & 500x_4 & -512x_3 & 12x_2 & 0 & 0\\
0 & 0 & 500x_3 & -512x_2 & 12x_1 & 0\\
0 & 0 & 0 & -500x_2 & 512x_1 & 9\\
\end{pmatrix}

In [ ]:
import numpy as np #Se importa la biblioteca de numpy para hacer las operaciones de vectores

def jacobi(A,b,x,imax =100,tol=1e-8) :
  '''
  El metodo de Jacobi es un metodo iterativo para resolver sistemas de ecuaciones
  lineales. Es recomendable que el sistema sea diagonalmente dominante
  Argumentos:
  ---
  A es la matriz de coeficientes
  b es el vector de constantes
  x es el vector inicial
  imax es el numero maximo de iteraciones
  tol es la tolerancia
  Devuelve el consunto solucion
  '''
  D=np.diag(A) #se obtiene la matriz D que es la diagonal de A
  R=A-np.diagflat(D) #se obtiene la matriz R con el resto de D
  cumple = False
  k=0
  #se hace el ciclo para iterar hasta que se cumpla el criterio de convergencia
  while (not cumple and k< imax):
     xk1 =(b-np.dot(R,x))/D #se aplica la ecuacion iterativa de Jacobi
     norma =np.linalg.norm(x- xk1 ) #se calcula la norma euclidea
     print (' iteracion :{} - >{} norma {} '.format(k,x,norma)) #se muestra cada iteracion
     cumple =norma < tol #se valida el criterio de convergencia
     x= xk1.copy() #se toma el valor calculado para la sig iteracion
     k +=1 #cuenta las iteraciones

  if k< imax :
    return x #retorna el conjunto solucion
  else :
    raise ValueError ( 'El sistema no converge ')

In [ ]:
#se crea la matriz de coeficientes del sistema
A = np.array([[ -512 ,12 ,0 ,0 ,0] ,
                [500 , -512 ,12 ,0 ,0] ,
                [0 ,500 , -512 ,12 ,0] ,
                [0 ,0 ,500 , -512 ,12] ,
                [0 ,0 ,0 , -500 ,512]])
#se crea el vector de las constantes del sistema
b = np.array([0 ,0 ,0 ,0 ,9])
#se crea el vector inicial
x = np.array([0 ,0 ,0 ,0 ,0])
#se llama al metodo de jacobi
x= jacobi(A,b,x)
print('\n\nSolucion : ',x)

 iteracion :0 - >[0 0 0 0 0] norma 0.017578125 
 iteracion :1 - >[-0.         -0.         -0.         -0.          0.01757812] norma 0.0004119873046875 
 iteracion :2 - >[-0.         -0.         -0.          0.00041199  0.01757812] norma 0.00040244720698264793 
 iteracion :3 - >[-0.00000000e+00 -0.00000000e+00  9.65595245e-06  4.11987305e-04
  1.79804564e-02] norma 1.8860639955397488e-05 
 iteracion :4 - >[-0.00000000e+00  2.26311386e-07  9.65595245e-06  4.30846587e-04
  1.79804564e-02] norma 1.842919899944634e-05 
 iteracion :5 - >[5.30417310e-09 2.26311386e-07 1.03189741e-05 4.30846587e-04
 1.79988736e-02] norma 1.0793356680990857e-06 
 iteracion :6 - >[5.30417310e-09 2.47030812e-07 1.03189741e-05 4.31925724e-04
 1.79988736e-02] norma 1.0548275284568573e-06 
 iteracion :7 - >[5.78978465e-09 2.47030812e-07 1.03645002e-05 4.31925724e-04
 1.79999275e-02] norma 6.917571784739033e-08 
 iteracion :8 - >[5.78978465e-09 2.48572059e-07 1.03645002e-05 4.31994882e-04
 1.79999275e-02] norma 6.76

In [ ]:
def gaussSeidel(A,b,x, imax =100 , tol =1e-8) :
  '''
  El metodo de Gauss Seidel es un metodo iterativo para resolver sistemas de ecuaciones
  lineales. Es recomendable que el sistema sea diagonalmente dominante
  Argumentos:
  ---
  A es la matriz de coeficientes
  b es el vector de constantes
  x es el vector inicial
  imax es el numero maximo de iteraciones
  tol es la tolerancia
  Devuelve el conjunto solucion
  '''
  L=np.tril(A) #se obtiene la matriz triangular inferior
  U=A-L #se obtiene la matriz triangular superior
  Linv =np.linalg.inv(L) #se obtiene la inversa de L
  cumple = False
  k=0
  #se hacen las iteraciones hasta cumplir con el criterio de convergencia
  while (not cumple and k< imax):
    xk1 =np.dot(Linv,b-np.dot(U,x)) #se aplica la ecuacion iterativa de Gauss Seidel
    norma =np.linalg.norm(x- xk1) #se obtiene la norma euclidea
    print (' iteracion :{} - >{} norma {} '.format(k,x, norma )) #se muestra cada iteracion
    cumple =norma < tol #se valida el criterio de convergencia
    x= xk1.copy() #se usa el valor obtenido para la sig iteracion
    k +=1 #se cuentan las iteraciones
 
  if k< imax :
    return x #retorna el conjunto solucion
  else :
    raise ValueError( 'El sistema no converge ')

In [ ]:
A = np. array ([[ -512 ,12 ,0 ,0 ,0] ,
                [500 , -512 ,12 ,0 ,0] ,
                [0 ,500 , -512 ,12 ,0] ,
                [0 ,0 ,500 , -512 ,12] ,
                [0 ,0 ,0 , -500 ,512]])
b = np. array ([0 ,0 ,0 ,0 ,9])
x = np. array ([0 ,0 ,0 ,0 ,0])
x= gaussSeidel (A,b,x)
print ( '\n\nSolucion : ',x)

 iteracion :0 - >[0 0 0 0 0] norma 0.017578125 
 iteracion :1 - >[0.         0.         0.         0.         0.01757812] norma 0.000575850723898146 
 iteracion :2 - >[0.         0.         0.         0.00041199 0.01798046] norma 2.8073220164515078e-05 
 iteracion :3 - >[0.00000000e+00 0.00000000e+00 9.65595245e-06 4.30846587e-04
 1.79988736e-02] norma 1.663111234926709e-06 
 iteracion :4 - >[0.00000000e+00 2.26311386e-07 1.03189741e-05 4.31925724e-04
 1.79999275e-02] norma 1.0896921936203857e-07 
 iteracion :5 - >[5.30417310e-09 2.47030812e-07 1.03645002e-05 4.31994882e-04
 1.79999950e-02] norma 7.373382462926921e-09 


Solucion :  [5.78978465e-09 2.48572059e-07 1.03676262e-05 4.31999518e-04
 1.79999995e-02]


In [ ]:
def sor(A,b,x,w=1,imax =100,tol=1e-8) :
  '''
  El metodo SOR es un metodo iterativo para resolver sistemas de ecuaciones
  lineales. Se utiliza el factor w para hacer la relajacion
  Argumentos:
  ---
  A es la matriz de coeficientes
  b es el vector de constantes
  x es el vector inicial
  w es el facor de relajacion 
  0<w<1 sub relajacion para hacer convergente el sistema
  1<w<2 sobre relajacion para acelerar la convergencia
  imax es el numero maximo de iteraciones
  tol es la tolerancia
  Devuelve el conjunto solucion
  '''
  cumple = False
  n=A.shape[0]
  k=0
  #se hace el ciclo de las iteraciones
  while ( not cumple and k< imax ):
    xk1 = np.zeros(n)
    for i in range(n):
      s1 = np.dot(A[i ,:i], xk1 [:i]) #primer suma
      s2 = np.dot(A[i,i+1:], x[i +1:]) #segunda suma
      xk1[i] = (b[i]-s1 -s2)/A[i, i]*w+(1 -w)*x[i] #se aplica la ecuacion iterativa de SOR
 
    norma =np.linalg.norm(x- xk1 ) #se calcula la norma euclidea
    print (' iteracion :{} - >{} norma {} '.format(k,xk1,norma)) #se muestra cada iteracion
    cumple =norma < tol #se valida el criterio de convergencia
    x= xk1 #se usa el valor calculado para la sig iteracion
    k +=1 #se cuentan las iteraciones

  if k< imax :
    return x #retorna el conjunto solucion
  else :
    raise ValueError( 'El sistema no converge ')

In [ ]:
A = np. array ([[ -512 ,12 ,0 ,0 ,0] ,
                [500 , -512 ,12 ,0 ,0] ,
                [0 ,500 , -512 ,12 ,0] ,
                [0 ,0 ,500 , -512 ,12] ,
                [0 ,0 ,0 , -500 ,512]])
b = np. array ([0 ,0 ,0 ,0 ,9])
x = np. array ([0 ,0 ,0 ,0 ,0])

w =1.1
x= sor(A,b,x,w)
print ( '\n\nSolucion : ',x)

 iteracion :0 - >[-0.         -0.         -0.         -0.          0.01933594] norma 0.0193359375 
 iteracion :1 - >[0.         0.         0.         0.0004985  0.01793785] norma 0.0014843060791567123 
 iteracion :2 - >[-0.00000000e+00 -0.00000000e+00  1.28520727e-05  4.26415586e-04
  1.80002164e-02] norma 9.618722250697878e-05 
 iteracion :3 - >[0.00000000e+00 3.31342500e-07 1.00642539e-05 4.32237732e-04
 1.80002337e-02] norma 6.463698824444121e-06 
 iteracion :4 - >[8.54242382e-09 2.35511227e-07 1.03901942e-05 4.32006094e-04
 1.79999832e-02] norma 4.815903680254931e-07 
 iteracion :5 - >[5.21753144e-09 2.49925842e-07 1.03671127e-05 4.31998004e-04
 1.79999995e-02] norma 3.2937161890614256e-08 
 iteracion :6 - >[5.92164747e-09 2.48645685e-07 1.03678371e-05 4.32000013e-04
 1.80000001e-02] norma 2.639718926897102e-09 


Solucion :  [5.92164747e-09 2.48645685e-07 1.03678371e-05 4.32000013e-04
 1.80000001e-02]
