<a href="https://colab.research.google.com/github/jcjimenezb123/MetodosNumericosPython/blob/master/SistemasEcuacionesLineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sistemas de ecuaciones lineales

##Métodos Directos

Resolver el siguiente sistema lineal

$$
\begin{array}{ccccccc}
x&+&y&+&z&=&6\\
&&2y&+&5z&=&-4\\
2x&+&5y&-&z&=&27\\
\end{array}
$$

In [1]:
import numpy as np
import scipy as sp

In [2]:
#se crea la matriz de coeficientes del sistema a resolver
A=np.array([[1,1,1],
            [0,2,5],
            [2,5,-1]])
#se crea el vector de los terminos independientes
b=np.array([[6,-4,27]])

In [9]:
Ab=np.concatenate((A,b.T),axis=1) #se crea la matriz extendida concatenando el vector b como una columna (axis=1)
n=np.size(A,axis=1) #regresa el numero de columnas de A, es decir, el numero de incognitas

3

Validar si tiene solucion unica por el teorema de **Rouche-Frobenius**

In [10]:
solucion_unica = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)==n
solucion_unica

True

Resolver el sistema usando el metodo de **Gauss-Jordan**

In [11]:
import sympy as sy

In [13]:
reduccion,_=sy.Matrix(Ab).rref() #rref (row reduced echelon form), es decir, el metodo de Gauss-Jordan
reduccion[:,n]

Matrix([
[ 5],
[ 3],
[-2]])

por lo tanto el conjunto solucion es

* $x=5$
* $y=3$
* $z=-2$

Aplicando el metodo de **inversa-multiplicacion**

In [14]:
#se obtiene la inversa de la matriz de coeficientes A
Ainv=np.linalg.inv(A)
Ainv

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

In [16]:
x=Ainv.dot(b.T) #se multiplica la inversa de A por el vector b
x

array([[ 5.],
       [ 3.],
       [-2.]])

Aplicando la regla de **Cramer**

In [20]:
DetA=np.linalg.det(A)
x=np.empty(n)

for i in range(n):
  Ax=A.copy()
  Ax[:,i]=b.copy()
  DetAx=np.linalg.det(Ax)
  x[i]=DetAx/DetA

print(x)

[ 5.  3. -2.]


Se aplica la funcion **solve** de numpy

In [21]:
x=np.linalg.solve(A,b.T)
x

array([[ 5.],
       [ 3.],
       [-2.]])

#Sistemas homogeneos $Ax=0$

Balancear la siguiente ecuación química

$$
x_1Pb(N_3)_2 + x_2Cr(MnO_4)_2 \rightarrow x_3Cr_2O_3 + x_4MnO_2 + x_5Pb_3O_4 + x_6NO
$$

Balance por elemento

* $Pb: x_1 = 3x_5 \Rightarrow x1–3x_5 = 0$
* $N: 6x_1 = x_6 \Rightarrow 6x_1 -x_6 = 0$
* $Cr: x_2 = 2x_3 \Rightarrow x_2–2x_3 = 0$
* $Mn: 2x_2 = x_4 \Rightarrow 2x_2–x_4 = 0$
* $O: 8x_2 = 3x_3 +2x_4 +4x_5 +x_6 \Rightarrow 8x_2 -3x_3 -2x_4 -4x_5 -x_6 = 0$

El sistema de ecuaciones lineales es

$$
\begin{pmatrix}
1& 0& 0& 0& -3& 0\\
6& 0& 0& 0& 0& -1\\
0& 1& -2& 0& 0& 0\\
0& 2& 0& -1& 0& 0\\
0& 8& -3& -2& -4& -1
\end{pmatrix}
$$

In [2]:
import numpy as np
A=np.array([[1 , 0, 0, 0,-3, 0 ],
            [ 6 , 0, 0, 0, 0,-1 ],
            [ 0 , 1,-2, 0, 0, 0 ],
            [ 0 , 2, 0,-1, 0, 0 ],
            [ 0 , 8,-3,-2,-4,-1 ]])

b=np.array([[0 ,0 ,0 ,0 ,0]])

In [3]:
Ab=np.concatenate((A,b.T),axis=1)
n=np.size(A,axis=1)

In [4]:
solucion_unica = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)==n
solucion_unica

False

In [5]:
solucion_multiple = np.linalg.matrix_rank(A)==np.linalg.matrix_rank(Ab)<n
solucion_multiple

True

In [6]:
import sympy as sy

reduccion,_=sy.Matrix(Ab).rref()
reduccion

Matrix([
[1, 0, 0, 0, 0,   -1/6, 0],
[0, 1, 0, 0, 0, -22/45, 0],
[0, 0, 1, 0, 0, -11/45, 0],
[0, 0, 0, 1, 0, -44/45, 0],
[0, 0, 0, 0, 1,  -1/18, 0]])

Por lo tanto el sistema tiene multiples soluciones y guarda las siguientes proporciones

* $x_1=1/6x_6$
* $x_2=22/45x_6$
* $x_3=11/45x_6$
* $x_4=44/45x_6$
* $x_5=1/18x_6$

el conjunto solucion queda expresado como

$$
(1/6x_6,22/45x_6,11/45x_6,44/45x_6,1/18x_6,x_6)
$$

para resolver el problema del balanceo de la reaccion quimica se debe buscar un valor de $x_6$ de tal manera que los valores del resto de las incognitas sea un entero.

por ejemplo $x_6=90$



In [13]:
x6=90
x1=-x6*reduccion[0,-2]
x2=-x6*reduccion[1,-2]
x3=-x6*reduccion[2,-2]
x4=-x6*reduccion[3,-2]
x5=-x6*reduccion[4,-2]

print(x1,x2,x3,x4,x5,x6)

15 44 22 88 5 90


Por lo tanto la reaccion balanceada es

$$
15Pb(N_3)_2 + 44Cr(MnO_4)_2 \rightarrow 22Cr_2O_3 + 88MnO_2 + 5Pb_3O_4 + 90NO
$$